export enum measurements {
  gram = 'gram',
  grams = 'grams',
  tbsp = 'tbsp',
  tbsps = 'tbsps',
  cup = 'cup',
  cups = 'cups',
  pint = 'pint',
  pints = 'pints',
  quart = 'quart',
  container = 'container',
  kg = 'kg',
  lb = 'lb',
  oz = 'oz',
  slice = 'slice',
  slices = 'slices',
  large = 'large',
  tsp = 'tsp',
  tsps = 'tsps',
  package = 'package',
  packages = 'packages',
  link = 'link',
  links = 'links',
  inches = 'inches',
  inch = 'inch',
  medium = 'medium',
  serving = 'serving',
  servings = 'servings',
  piece = 'piece',
  pieces = 'pieces',
  bottle = 'bottle',
  bottles = 'bottles',
  can = 'can',
  cans = 'cans'
}

export const DIMENSIONS = [
  'gram',
  'grams',
  'tbsp',
  'tbsps',
  'cup',
  'cups',
  'pint',
  'pints',
  'quart',
  'container',
  'kg',
  'lb',
  'oz',
  'slice',
  'slices',
  'large',
  'tsp',
  'tsps',
  'package',
  'packages',
  'link',
  'links',
  'inches',
  'inch',
  'medium',
  'serving',
  'servings',
  'piece',
  'pieces',
  'bottle',
  'bottles',
  'can',
  'cans'
];

export enum formControls {
  servingSizeAmount = 'servingSizeAmount',
  servingPerContainer = 'servingPerContainer',
  calories = 'calories',
  totalFatGrams = 'totalFatGrams',
  totalFatPercent = 'totalFatPercent',
  saturatedFatGrams = 'saturatedFatGrams',
  saturatedFatPercent = 'saturatedFatPercent',
  transFatGrams = 'transFatGrams',
  transFatPercent = 'transFatPercent',
  polyunsaturatedFatGrams = 'polyunsaturatedFatGrams',
  polyunsaturatedFatPercent = 'polyunsaturatedFatPercent',
  monounsaturatedFatGrams = 'monounsaturatedFatGrams',
  monounsaturatedFatPercent = 'monounsaturatedFatPercent',
  cholesterolGrams = 'cholesterolGrams',
  cholesterolPercent = 'cholesterolPercent',
  sodiumGrams = 'sodiumGrams',
  sodiumPercent = 'sodiumPercent',
  potassiumGrams = 'potassiumGrams',
  potassiumPercent = 'potassiumPercent',
  totalCarbohydratesGrams = 'totalCarbohydratesGrams',
  totalCarbohydratesPercent = 'totalCarbohydratesPercent',
  dietaryFiberGrams = 'dietaryFiberGrams',
  dietaryFiberPercent = 'dietaryFiberPercent',
  proteinGrams = 'proteinGrams',
  proteinPercent = 'proteinPercent',
  niacinGrams = 'niacinGrams',
  niacinPercent = 'niacinPercent',
  phosphorusGrams = 'phosphorusGrams',
  phosphorusPercent = 'phosphorusPercent',
  calciumGrams = 'calciumGrams',
  calciumPercent = 'calciumPercent',
  ironGrams = 'ironGrams',
  ironPercent = 'ironPercent',
  magnesiumGrams = 'magnesiumGrams',
  magnesiumPercent = 'magnesiumPercent',
  manganeseGrams = 'manganeseGrams',
  manganesePercent = 'manganesePercent',
  vitaminAGrams = 'vitaminAGrams',
  vitaminAPercent = 'vitaminAPercent',
  vitaminBGrams = 'vitaminBGrams',
  vitaminBPercent = 'vitaminBPercent',
  vitaminCGrams = 'vitaminCGrams',
  vitaminCPercent = 'vitaminCPercent',
  vitaminDGrams = 'vitaminDGrams',
  vitaminDPercent = 'vitaminDPercent',
  vitaminEGrams = 'vitaminEGrams',
  vitaminEPercent = 'vitaminEPercent',
  sugarTotalGrams = 'sugarTotalGrams',
  sugarTotalPercent = 'sugarTotalPercent',
  sugarAddedGrams = 'sugarAddedGrams',
  sugarAddedPercent = 'sugarAddedPercent',
  sugarAlcoholTotalGrams = 'sugarAlcoholTotalGrams',
  sugarAlcoholTotalPercent = 'sugarAlcoholTotalPercent',
  sugarAlcoholAddedGrams = 'sugarAlcoholAddedGrams',
  sugarAlcoholAddedPercent = 'sugarAlcoholAddedPercent',

}