/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IIngredient } from "./interfaces/IIngredient";
import { IRecipeInputs } from "./interfaces/IRecipeInputs";
export namespace Components {
    interface AppHome {
    }
    interface AppRecipeAdd {
    }
    interface AppRecipeEdit {
    }
    interface AppRecipeInfo {
    }
    interface AppRecipeList {
    }
    interface AppRoot {
    }
    interface AppUserProfile {
    }
    interface CategoryChips {
    }
    interface IngredientsInputs {
        "ingredients": IIngredient[];
    }
    interface RecipeInputs {
        "category": string;
        "name": string;
    }
    interface RecipeItem {
        "calories": number;
        "image": string;
        "name": string;
    }
    interface StepsInputs {
        "steps": string[];
    }
    interface UtensilsInputs {
        "utensils": string[];
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRecipeAddElement extends Components.AppRecipeAdd, HTMLStencilElement {
    }
    var HTMLAppRecipeAddElement: {
        prototype: HTMLAppRecipeAddElement;
        new (): HTMLAppRecipeAddElement;
    };
    interface HTMLAppRecipeEditElement extends Components.AppRecipeEdit, HTMLStencilElement {
    }
    var HTMLAppRecipeEditElement: {
        prototype: HTMLAppRecipeEditElement;
        new (): HTMLAppRecipeEditElement;
    };
    interface HTMLAppRecipeInfoElement extends Components.AppRecipeInfo, HTMLStencilElement {
    }
    var HTMLAppRecipeInfoElement: {
        prototype: HTMLAppRecipeInfoElement;
        new (): HTMLAppRecipeInfoElement;
    };
    interface HTMLAppRecipeListElement extends Components.AppRecipeList, HTMLStencilElement {
    }
    var HTMLAppRecipeListElement: {
        prototype: HTMLAppRecipeListElement;
        new (): HTMLAppRecipeListElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppUserProfileElement extends Components.AppUserProfile, HTMLStencilElement {
    }
    var HTMLAppUserProfileElement: {
        prototype: HTMLAppUserProfileElement;
        new (): HTMLAppUserProfileElement;
    };
    interface HTMLCategoryChipsElement extends Components.CategoryChips, HTMLStencilElement {
    }
    var HTMLCategoryChipsElement: {
        prototype: HTMLCategoryChipsElement;
        new (): HTMLCategoryChipsElement;
    };
    interface HTMLIngredientsInputsElement extends Components.IngredientsInputs, HTMLStencilElement {
    }
    var HTMLIngredientsInputsElement: {
        prototype: HTMLIngredientsInputsElement;
        new (): HTMLIngredientsInputsElement;
    };
    interface HTMLRecipeInputsElement extends Components.RecipeInputs, HTMLStencilElement {
    }
    var HTMLRecipeInputsElement: {
        prototype: HTMLRecipeInputsElement;
        new (): HTMLRecipeInputsElement;
    };
    interface HTMLRecipeItemElement extends Components.RecipeItem, HTMLStencilElement {
    }
    var HTMLRecipeItemElement: {
        prototype: HTMLRecipeItemElement;
        new (): HTMLRecipeItemElement;
    };
    interface HTMLStepsInputsElement extends Components.StepsInputs, HTMLStencilElement {
    }
    var HTMLStepsInputsElement: {
        prototype: HTMLStepsInputsElement;
        new (): HTMLStepsInputsElement;
    };
    interface HTMLUtensilsInputsElement extends Components.UtensilsInputs, HTMLStencilElement {
    }
    var HTMLUtensilsInputsElement: {
        prototype: HTMLUtensilsInputsElement;
        new (): HTMLUtensilsInputsElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-recipe-add": HTMLAppRecipeAddElement;
        "app-recipe-edit": HTMLAppRecipeEditElement;
        "app-recipe-info": HTMLAppRecipeInfoElement;
        "app-recipe-list": HTMLAppRecipeListElement;
        "app-root": HTMLAppRootElement;
        "app-user-profile": HTMLAppUserProfileElement;
        "category-chips": HTMLCategoryChipsElement;
        "ingredients-inputs": HTMLIngredientsInputsElement;
        "recipe-inputs": HTMLRecipeInputsElement;
        "recipe-item": HTMLRecipeItemElement;
        "steps-inputs": HTMLStepsInputsElement;
        "utensils-inputs": HTMLUtensilsInputsElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRecipeAdd {
    }
    interface AppRecipeEdit {
    }
    interface AppRecipeInfo {
    }
    interface AppRecipeList {
    }
    interface AppRoot {
    }
    interface AppUserProfile {
    }
    interface CategoryChips {
        "onCategoryCompleted"?: (event: CustomEvent<string>) => void;
    }
    interface IngredientsInputs {
        "ingredients"?: IIngredient[];
        "onIngredientsInputData"?: (event: CustomEvent<IIngredient[]>) => void;
    }
    interface RecipeInputs {
        "category"?: string;
        "name"?: string;
        "onRecipeInputData"?: (event: CustomEvent<IRecipeInputs>) => void;
    }
    interface RecipeItem {
        "calories"?: number;
        "image"?: string;
        "name"?: string;
    }
    interface StepsInputs {
        "onStepsInputData"?: (event: CustomEvent<string[]>) => void;
        "steps"?: string[];
    }
    interface UtensilsInputs {
        "onUtensilInputData"?: (event: CustomEvent<string[]>) => void;
        "utensils"?: string[];
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-recipe-add": AppRecipeAdd;
        "app-recipe-edit": AppRecipeEdit;
        "app-recipe-info": AppRecipeInfo;
        "app-recipe-list": AppRecipeList;
        "app-root": AppRoot;
        "app-user-profile": AppUserProfile;
        "category-chips": CategoryChips;
        "ingredients-inputs": IngredientsInputs;
        "recipe-inputs": RecipeInputs;
        "recipe-item": RecipeItem;
        "steps-inputs": StepsInputs;
        "utensils-inputs": UtensilsInputs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-recipe-add": LocalJSX.AppRecipeAdd & JSXBase.HTMLAttributes<HTMLAppRecipeAddElement>;
            "app-recipe-edit": LocalJSX.AppRecipeEdit & JSXBase.HTMLAttributes<HTMLAppRecipeEditElement>;
            "app-recipe-info": LocalJSX.AppRecipeInfo & JSXBase.HTMLAttributes<HTMLAppRecipeInfoElement>;
            "app-recipe-list": LocalJSX.AppRecipeList & JSXBase.HTMLAttributes<HTMLAppRecipeListElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-user-profile": LocalJSX.AppUserProfile & JSXBase.HTMLAttributes<HTMLAppUserProfileElement>;
            "category-chips": LocalJSX.CategoryChips & JSXBase.HTMLAttributes<HTMLCategoryChipsElement>;
            "ingredients-inputs": LocalJSX.IngredientsInputs & JSXBase.HTMLAttributes<HTMLIngredientsInputsElement>;
            "recipe-inputs": LocalJSX.RecipeInputs & JSXBase.HTMLAttributes<HTMLRecipeInputsElement>;
            "recipe-item": LocalJSX.RecipeItem & JSXBase.HTMLAttributes<HTMLRecipeItemElement>;
            "steps-inputs": LocalJSX.StepsInputs & JSXBase.HTMLAttributes<HTMLStepsInputsElement>;
            "utensils-inputs": LocalJSX.UtensilsInputs & JSXBase.HTMLAttributes<HTMLUtensilsInputsElement>;
        }
    }
}
