/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRecipeDaily {
        "calories": number;
        "image": string;
        "name": string;
    }
    interface AppRecipeInfo {
    }
    interface AppRecipeList {
    }
    interface AppRoot {
    }
    interface AppUserProfile {
    }
    interface CategoryChips {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRecipeDailyElement extends Components.AppRecipeDaily, HTMLStencilElement {
    }
    var HTMLAppRecipeDailyElement: {
        prototype: HTMLAppRecipeDailyElement;
        new (): HTMLAppRecipeDailyElement;
    };
    interface HTMLAppRecipeInfoElement extends Components.AppRecipeInfo, HTMLStencilElement {
    }
    var HTMLAppRecipeInfoElement: {
        prototype: HTMLAppRecipeInfoElement;
        new (): HTMLAppRecipeInfoElement;
    };
    interface HTMLAppRecipeListElement extends Components.AppRecipeList, HTMLStencilElement {
    }
    var HTMLAppRecipeListElement: {
        prototype: HTMLAppRecipeListElement;
        new (): HTMLAppRecipeListElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppUserProfileElement extends Components.AppUserProfile, HTMLStencilElement {
    }
    var HTMLAppUserProfileElement: {
        prototype: HTMLAppUserProfileElement;
        new (): HTMLAppUserProfileElement;
    };
    interface HTMLCategoryChipsElement extends Components.CategoryChips, HTMLStencilElement {
    }
    var HTMLCategoryChipsElement: {
        prototype: HTMLCategoryChipsElement;
        new (): HTMLCategoryChipsElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-recipe-daily": HTMLAppRecipeDailyElement;
        "app-recipe-info": HTMLAppRecipeInfoElement;
        "app-recipe-list": HTMLAppRecipeListElement;
        "app-root": HTMLAppRootElement;
        "app-user-profile": HTMLAppUserProfileElement;
        "category-chips": HTMLCategoryChipsElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRecipeDaily {
        "calories"?: number;
        "image"?: string;
        "name"?: string;
    }
    interface AppRecipeInfo {
    }
    interface AppRecipeList {
    }
    interface AppRoot {
    }
    interface AppUserProfile {
    }
    interface CategoryChips {
        "onCategoryCompleted"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-recipe-daily": AppRecipeDaily;
        "app-recipe-info": AppRecipeInfo;
        "app-recipe-list": AppRecipeList;
        "app-root": AppRoot;
        "app-user-profile": AppUserProfile;
        "category-chips": CategoryChips;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-recipe-daily": LocalJSX.AppRecipeDaily & JSXBase.HTMLAttributes<HTMLAppRecipeDailyElement>;
            "app-recipe-info": LocalJSX.AppRecipeInfo & JSXBase.HTMLAttributes<HTMLAppRecipeInfoElement>;
            "app-recipe-list": LocalJSX.AppRecipeList & JSXBase.HTMLAttributes<HTMLAppRecipeListElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-user-profile": LocalJSX.AppUserProfile & JSXBase.HTMLAttributes<HTMLAppUserProfileElement>;
            "category-chips": LocalJSX.CategoryChips & JSXBase.HTMLAttributes<HTMLCategoryChipsElement>;
        }
    }
}
