/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IDaily,
} from './interfaces';

export namespace Components {
  interface AppCreateFood {}
  interface AppDaily {
    'breakfastCalories': number;
    'breakfastSnackCalories': number;
    'daily': IDaily;
    'dinnerCalories': number;
    'dinnerSnackCalories': number;
    'lunchCalories': number;
    'lunchSnackCalories': number;
  }
  interface AppFoodList {}
  interface AppHome {}
  interface AppRoot {}
}

declare global {


  interface HTMLAppCreateFoodElement extends Components.AppCreateFood, HTMLStencilElement {}
  var HTMLAppCreateFoodElement: {
    prototype: HTMLAppCreateFoodElement;
    new (): HTMLAppCreateFoodElement;
  };

  interface HTMLAppDailyElement extends Components.AppDaily, HTMLStencilElement {}
  var HTMLAppDailyElement: {
    prototype: HTMLAppDailyElement;
    new (): HTMLAppDailyElement;
  };

  interface HTMLAppFoodListElement extends Components.AppFoodList, HTMLStencilElement {}
  var HTMLAppFoodListElement: {
    prototype: HTMLAppFoodListElement;
    new (): HTMLAppFoodListElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-create-food': HTMLAppCreateFoodElement;
    'app-daily': HTMLAppDailyElement;
    'app-food-list': HTMLAppFoodListElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppCreateFood extends JSXBase.HTMLAttributes<HTMLAppCreateFoodElement> {}
  interface AppDaily extends JSXBase.HTMLAttributes<HTMLAppDailyElement> {
    'breakfastCalories'?: number;
    'breakfastSnackCalories'?: number;
    'daily'?: IDaily;
    'dinnerCalories'?: number;
    'dinnerSnackCalories'?: number;
    'lunchCalories'?: number;
    'lunchSnackCalories'?: number;
  }
  interface AppFoodList extends JSXBase.HTMLAttributes<HTMLAppFoodListElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}

  interface IntrinsicElements {
    'app-create-food': AppCreateFood;
    'app-daily': AppDaily;
    'app-food-list': AppFoodList;
    'app-home': AppHome;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


