/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IDaily } from "./interfaces";
export namespace Components {
    interface AppDailyEntry {
    }
    interface AppDailyList {
        "breakfastCalories": number;
        "breakfastSnackCalories": number;
        "daily": IDaily;
        "dinnerCalories": number;
        "dinnerSnackCalories": number;
        "lunchCalories": number;
        "lunchSnackCalories": number;
        "today": string;
    }
    interface AppFoodList {
    }
    interface AppFormFood {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppViewFood {
    }
}
declare global {
    interface HTMLAppDailyEntryElement extends Components.AppDailyEntry, HTMLStencilElement {
    }
    var HTMLAppDailyEntryElement: {
        prototype: HTMLAppDailyEntryElement;
        new (): HTMLAppDailyEntryElement;
    };
    interface HTMLAppDailyListElement extends Components.AppDailyList, HTMLStencilElement {
    }
    var HTMLAppDailyListElement: {
        prototype: HTMLAppDailyListElement;
        new (): HTMLAppDailyListElement;
    };
    interface HTMLAppFoodListElement extends Components.AppFoodList, HTMLStencilElement {
    }
    var HTMLAppFoodListElement: {
        prototype: HTMLAppFoodListElement;
        new (): HTMLAppFoodListElement;
    };
    interface HTMLAppFormFoodElement extends Components.AppFormFood, HTMLStencilElement {
    }
    var HTMLAppFormFoodElement: {
        prototype: HTMLAppFormFoodElement;
        new (): HTMLAppFormFoodElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppViewFoodElement extends Components.AppViewFood, HTMLStencilElement {
    }
    var HTMLAppViewFoodElement: {
        prototype: HTMLAppViewFoodElement;
        new (): HTMLAppViewFoodElement;
    };
    interface HTMLElementTagNameMap {
        "app-daily-entry": HTMLAppDailyEntryElement;
        "app-daily-list": HTMLAppDailyListElement;
        "app-food-list": HTMLAppFoodListElement;
        "app-form-food": HTMLAppFormFoodElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-view-food": HTMLAppViewFoodElement;
    }
}
declare namespace LocalJSX {
    interface AppDailyEntry {
    }
    interface AppDailyList {
        "breakfastCalories"?: number;
        "breakfastSnackCalories"?: number;
        "daily"?: IDaily;
        "dinnerCalories"?: number;
        "dinnerSnackCalories"?: number;
        "lunchCalories"?: number;
        "lunchSnackCalories"?: number;
        "onUpdatedDailyEntry"?: (event: CustomEvent<any>) => void;
        "today"?: string;
    }
    interface AppFoodList {
    }
    interface AppFormFood {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppViewFood {
    }
    interface IntrinsicElements {
        "app-daily-entry": AppDailyEntry;
        "app-daily-list": AppDailyList;
        "app-food-list": AppFoodList;
        "app-form-food": AppFormFood;
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-view-food": AppViewFood;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-daily-entry": LocalJSX.AppDailyEntry & JSXBase.HTMLAttributes<HTMLAppDailyEntryElement>;
            "app-daily-list": LocalJSX.AppDailyList & JSXBase.HTMLAttributes<HTMLAppDailyListElement>;
            "app-food-list": LocalJSX.AppFoodList & JSXBase.HTMLAttributes<HTMLAppFoodListElement>;
            "app-form-food": LocalJSX.AppFormFood & JSXBase.HTMLAttributes<HTMLAppFormFoodElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-view-food": LocalJSX.AppViewFood & JSXBase.HTMLAttributes<HTMLAppViewFoodElement>;
        }
    }
}
